ASAP = "asap"
AskForLocation = "Or send me your location!"
AskToCompleteRegistration = "Hello there, we still need some information to serve you better."
Cancel = "Cancel"
CancellationAnswerNoLongerNeed = "No longer need a ride"
CancellationAnswerTakeAnotherMode = "Take another mobility mode"
CancellationAnswerWaitTooLong = "Too long waiting time"
CancellationAnswerWalk = "Decide to walk instead"
CancellationQuestionTitle = "Please tell us the reason why you cancelled this time."
ChangePickupTime = "Change pickup time"
CommandUnavailable = "Command unavailable"
Confirm = "Confirm"
Confirmation = "Language"
DriverAcceptedJob = "Driver accepts the job. Please meet at designated location {{.LocalTime}}"
Duration = "Duration"
English = "ðŸ‡ºðŸ‡¸ English"
EstTravelTime = "Estimated travel time"
HHMM = "at {{.hhmm}}."
Help = "Help"
HowDoYouLikeService = "How do you like our service this time?"
HowManyPassengers = "How many passengers?"
InXMin = "In {{.Min}} mins"
InputByMistake = "Input by mistake"
Japanese = "ðŸ‡¯ðŸ‡µ Japanese"
LanguageIsTheSame = "Your language is already {{.Lang}}."
LanguagePickerTitle = "Language selector"
LanguageSetTo = "Your language set to {{.Lang}}."
ListOfAvailableCommands = "List of available commands"
LocationOptions = "Location options"
NothingChanged = "Error, nothing changed"
PickFromListBelow = "Pick from the list below"
Pickup = "Pickup"
PickupLocation = "Pickup location?"
RegistrationComplete = "Your account is ready"
ReservationCancelled = "Your reservation cancelled."
ReservationConfirmation = "Your reservation: confirmation"
ReservationIncompleted = "The reservation isn't completed yet."
RideConfirmation = "Ride confirmation"
RideInitLine = "Need a ride now?"
RideIsDone = "The ride is done."
RideReservationCompleted = "Your ride reservation is done."
Thai = "ðŸ‡¹ðŸ‡­ Thai"
ThankYouSeeYouAgain = "Thank you for your feedback. We hope to see you again."
Time = "Time"
To = "To"
TravelMeter = "{{.Meter}} m"
TravelMeterWithFreeFlow = "{{.Meter}} m\n{{.FreeFlowMinute}} min w/o traffic"
TravelMinute = "{{.Min}} min"
VehicleWillPickYouUp = "{{.VehicleName}} by driver {{.DriverName}}, will pick you up."
WalkInstead = "I'll walk instead"
WelcomeAboard = "Welcome aboard!"
WhatIsYourEmail = "What's email?"
WhatIsYourFirstName = "What's your first name?"
WhatIsYourLastName = "What's your last name?"
When = "When?"
WhereTo = "Where to?"
WhichOne = "Which one do you prefer?"
Yes = "Yes"
