[ASAP]
hash = "sha1-261e4be27e3c714008c2ea33cd6a7cd65e312c66"
other = "ä»Šã™ã"

[AskForLocation]
hash = "sha1-a5fe081642f02cb713106d5ab30f2f0a30d73bc9"
other = "ç¾åœ¨åœ°ã‚’æ•™ãˆã¦ãã ã•ã„ï¼"

[AskToCompleteRegistration]
hash = "sha1-181c6d4e88ce9a547b5ce02d57a64075fb63bae3"
other = "ã‚ˆã‚Šè‰¯ã„ã‚µãƒ¼ãƒ“ã‚¹ã‚’æä¾›ã™ã‚‹ãŸã‚ã«ã€ã¾ã ã„ãã¤ã‹ã®æƒ…å ±ãŒå¿…è¦ã§ã™ã€‚ "

[Cancel]
hash = "sha1-77dfd2135f4db726c47299bb55be26f7f4525a46"
other = "ã‚­ãƒ£ãƒ³ã‚»ãƒ«"

[CancellationAnswerNoLongerNeed]
hash = "sha1-d8dbb17c96c3f71dd320836c73502fb93bb0ded8"
other = "ç§»å‹•ã®äºˆå®šãŒç„¡ããªã£ãŸ"

[CancellationAnswerTakeAnotherMode]
hash = "sha1-70bd0c2bd637d9cb1263e8f801679d7115a3abc0"
other = "ä»–ã®ä¹—ã‚Šç‰©ã«å¤‰æ›´ã—ãŸ"

[CancellationAnswerWaitTooLong]
hash = "sha1-6c80ed0636582dbdc6e9a4f339517ef00af33140"
other = "å¾…ã¡æ™‚é–“ãŒé•·ã™ããŸ"

[CancellationAnswerWalk]
hash = "sha1-1d4f99e0f74f807e65f82ff788265567fa63934b"
other = "å¾’æ­©ã«å¤‰æ›´ã—ãŸ"

[CancellationQuestionTitle]
hash = "sha1-f234df7d549da7563c348a1f134bec0632242463"
other = "ã‚­ãƒ£ãƒ³ã‚»ãƒ«ã—ãŸç†ç”±ã‚’æ•™ãˆã¦ãã ã•ã„ã€‚"

[ChangePickupTime]
hash = "sha1-6fe1b87d93c074860ffd6252c5fa5e0601086ba3"
other = "ãƒ”ãƒƒã‚¯ã‚¢ãƒƒãƒ—æ™‚é–“ã®å¤‰æ›´"

[CommandUnavailable]
hash = "sha1-bfed234d466faaa491252c3b967ea72e8febeb62"
other = "Command unavailable"

[Confirm]
hash = "sha1-04a212215ef9fbf686d280802eb81ee7a6e681cd"
other = "äº†è§£"

[Confirmation]
hash = "sha1-89b86ab0e66f527166d98df92ddbcf5416ed58f6"
other = "è¨€èªå¤‰æ›´"

[DriverAcceptedJob]
hash = "sha1-0b7257900992c0bfb8357f2933afdf55feb3b42b"
other = "ãƒ‰ãƒ©ã‚¤ãƒãƒ¼ãŒãƒªã‚¯ã‚¨ã‚¹ãƒˆã‚’ç¢ºèªã—ã¾ã—ãŸã€‚ã”æŒ‡å®šé ‚ã„ãŸå ´æ‰€ã§ãŠå¾…ã¡ãã ã•ã„ã€‚ {{.LocalTime}}"

[Duration]
hash = "sha1-1370004da76fa4f3b7a5180fd5436065ef4c7d5b"
other = "ç¶™ç¶š"

[English]
hash = "sha1-531f367102ee2e7e97b24eb8f4c017a7b95aa3c9"
other = "ğŸ‡ºğŸ‡¸ è‹±èª"

[EstTravelTime]
hash = "sha1-ca295a985b4ccd463c862da45bd05ff076925940"
other = "æ¨å®šæ‰€è¦æ™‚é–“"

[HHMM]
hash = "sha1-77e041e915eb683582c0a8d397be3b7b6ab20f82"
other = "ç´„ {{.hhmm}}."

[Help]
hash = "sha1-c47ae15370cfe1ed2781eedc1dc2547d12d9e972"
other = "ãƒ˜ãƒ«ãƒ—"

[HowDoYouLikeService]
hash = "sha1-82e9d183b6bd3d72201c7ffec1f30a5052485eca"
other = "ä»Šå›ã®ã‚µãƒ¼ãƒ“ã‚¹ã¯ã„ã‹ãŒã§ã—ãŸã‹ï¼Ÿ"

[HowManyPassengers]
hash = "sha1-2042168092b0cb32eee5bcf6489daec735b45896"
other = "ä½•äººã§ä¹—ã‚Šã¾ã™ã‹ï¼Ÿ"

[InXMin]
hash = "sha1-1b9afe7ecce7e97799fa26f9fbe507635d86d39d"
other = "{{.Min}} ä»¥å†…"

[InputByMistake]
hash = "sha1-1ac575d79dfb1e082ff3be03cc7ec8cb5dc8603a"
other = "å…¥åŠ›é–“é•ã„"

[Japanese]
hash = "sha1-568d976ca7ff3428d0c649cfc6f8129a91796b5a"
other = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èª"

[LanguageIsTheSame]
hash = "sha1-d4201bc6bf738be94f7f9f60025695136ac8623c"
other = "ã‚ãªãŸã®è¨€èªã¯ {{.Lang}}ã«è¨­å®šã•ã‚Œã¾ã—ãŸã€‚"

[LanguagePickerTitle]
hash = "sha1-0eae0a3940e209d57f6ecd4350292b0d1afcc384"
other = "ä½¿ç”¨è¨€èªå¤‰æ›´"

[LanguageSetTo]
hash = "sha1-aab5ce35b6cea5532c4299bf8a461ba9c48aac2e"
other = "è¨€èªãŒ{{.Lang}}ã«è¨­å®šã•ã‚Œã¾ã—ãŸã€‚"

[ListOfAvailableCommands]
hash = "sha1-a1553b62c1a5aab66de017cfefcbb8f8e6a983a1"
other = "ä½¿ç”¨å¯èƒ½ãªã‚³ãƒãƒ³ãƒ‰"

[LocationOptions]
hash = "sha1-af57e784f813f82867f9404ede10032f4ddbdcac"
other = "ãƒ­ã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã‚ªãƒ—ã‚·ãƒ§ãƒ³"

[NothingChanged]
hash = "sha1-4426d300412595c625518612913cdf3c711f1069"
other = "ã‚¨ãƒ©ãƒ¼ï¼å¤‰æ›´ã§ãã¾ã›ã‚“ã§ã—ãŸã€‚"

[PickFromListBelow]
hash = "sha1-085b13e5338096ef3ff6175e93aa573e659b8411"
other = "ãƒªã‚¹ãƒˆã‹ã‚‰é¸æŠ"

[Pickup]
hash = "sha1-a51122c1008c9b214f1e982f089eb0a2dd22fa29"
other = "ä¹—è»Šä½ç½®"

[PickupLocation]
hash = "sha1-adc67a6a7f319e02f4af6b15a052073a3a0f80b5"
other = "ä¹—è»Šå ´æ‰€ã¯ï¼Ÿ"

[RegistrationComplete]
hash = "sha1-9801e16715795e4a1a465a980416032e768bc6d5"
other = "ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã®æº–å‚™ãŒã§ãã¾ã—ãŸ"

[ReservationCancelled]
hash = "sha1-4d11bc874970e3dca3986247923dd720bb84ee12"
other = "ã‚ãªãŸã®äºˆç´„ãŒã‚­ãƒ£ãƒ³ã‚»ãƒ«ã•ã‚Œã¾ã—ãŸã€‚"

[ReservationConfirmation]
hash = "sha1-b15f1ccf3099374ee6a2a6ecf7cfe742857f9567"
other = "ã‚ãªãŸã®äºˆç´„ãŒç¢ºå®šã•ã‚Œã¾ã—ãŸã€‚"

[ReservationIncompleted]
hash = "sha1-6639ca8e87a4569638a99284e3073ec89533d7af"
other = "äºˆç´„ã¯ã¾ã å®Œäº†ã—ã¦ã„ã¾ã›ã‚“ã€‚"

[RideConfirmation]
hash = "sha1-f588dedd2103ee99cf256cea5bf414d955b005b5"
other = "ç¢ºèª"

[RideInitLine]
hash = "sha1-67567f35f862aa84fb9fdf3149d7fa737668d038"
other = "ä»Šã™ãä¹—ã‚Šã¾ã™ã‹ï¼Ÿ"

[RideIsDone]
hash = "sha1-bee614b3596a8c92525eb1bf20c83b618831549a"
other = "ä¹—è»ŠãŒå®Œäº†ã—ã¾ã—ãŸã€‚"

[RideReservationCompleted]
hash = "sha1-3775e2c9e3f2c7152641c52eadf14f8f4e319ae9"
other = "ä¹—è»Šäºˆç´„ãŒå®Œäº†ã—ã¾ã—ãŸã€‚"

[Thai]
hash = "sha1-01a0451b167c6cf484c04be7d570b2ac0cd6dd5e"
other = "ğŸ‡¹ğŸ‡­ ã‚¿ã‚¤"

[ThankYouSeeYouAgain]
hash = "sha1-b55f9a7f118909d91be03d26d6be72e0c2e53cf8"
other = "ãƒ•ã‚£ãƒ¼ãƒ‰ãƒãƒƒã‚¯ã‚’ã‚ã‚ŠãŒã¨ã†ã”ã–ã„ã¾ã™ã€‚ã¾ãŸã™ãã«ãŠç›®ã«ã‹ã‹ã‚Œã¾ã™ã‚ˆã†ã«ï¼"

[Time]
hash = "sha1-6c82e6dd86807ee3db07e3c82bec1ae1ce00b08b"
other = "æ™‚é–“"

[To]
hash = "sha1-ae79ea1e9c6391a9ed83a2e18a031b835feec0c9"
other = "ç›®çš„åœ°"

[TravelMeter]
hash = "sha1-4547d1acef093c449f91e129981cb51ee3fd4b58"
other = "{{.Meter}} m"

[TravelMeterWithFreeFlow]
hash = "sha1-2c5cda3d4aa29825e08b09ff7486205631906a14"
other = "{{.Meter}} m\n{{.FreeFlowMinute}} min w/o traffic"

[TravelMinute]
hash = "sha1-e9330ebf3f13f0e07de45b50b0b6a072157db2b9"
other = "{{.Min}} åˆ†"

[VehicleWillPickYouUp]
hash = "sha1-da2e2a4d04829d07c52714f94e8b6d4b343afc8d"
other = "{{.DriverName}}ãŒã‚ãªãŸã‚’{{.VehicleName}}: No. {{.LicensePlate}}ã§è¿ãˆã«ãã¾ã™ã€‚"

[WalkInstead]
hash = "sha1-aa0b91d9af024fa851a919365054a37dd556ed6d"
other = "ä»£ã‚ã‚Šã«æ­©ãã¾ã™ã€‚"

[WelcomeAboard]
hash = "sha1-389fa6a2c9a3cb8e81430d618d16526a649378de"
other = "ã‚ˆã†ã“ãï¼"

[WhatIsYourEmail]
hash = "sha1-eb7a3271d0718b38536f5e4783666c9482cd0a42"
other = "ã‚ãªãŸã®ãƒ¡ãƒ¼ãƒ«ã¯ä½•ã§ã™ã‹ï¼Ÿ"

[WhatIsYourFirstName]
hash = "sha1-484b8cfb5482beb3bda116e0627aaca1e693cc22"
other = "ã‚ãªãŸã®åã¯ä½•ã§ã™ã‹ï¼Ÿ"

[WhatIsYourLastName]
hash = "sha1-0e4224694477f72fca0d03a607a47e02d272d5a4"
other = "ã‚ãªãŸã®åå‰ã¯ä½•ã§ã™ã‹ï¼Ÿ"

[When]
hash = "sha1-b2028cfcc78f7fd44821aacab16481a32f1dfc70"
other = "ã„ã¤ä¹—ã‚Šã¾ã™ã‹ï¼Ÿ"

[WhereTo]
hash = "sha1-5bd0c21612751789aa6fbd8448cb52cdb0347d34"
other = "ã©ã“ã¸è¡Œãã¾ã™ã‹ï¼Ÿ"

[WhichOne]
hash = "sha1-45c75a477131234b3a52b3e6a6731ecd0ca724c3"
other = "ã©ã¡ã‚‰ã‹ãŠå¥½ã¿ã§ã™ã‹ï¼Ÿ"

[Yes]
hash = "sha1-5397e0583f14f6c88de06b1ef28f460a1fb5b0ae"
other = "ã¯ã„"

[WorkTable]
other = "ä»Šæ—¥ã®å‹¤å‹™æ™‚é–“ã¯{{.START_WORK_TIME}}ã‹ã‚‰{{.END_WORK_TIME}}ã¾ã§ã§ã€æ˜¼ä¼‘ã¿ã¯{{.START_BREAK_TIME}}ã‹ã‚‰{{.END_BREAK_TIME}}ã¾ã§ã§ã™ã€‚"

[JobID]
other = "äºˆç´„ç•ªå·"

[ThankYouForAnswer]
other = "ç­”ãˆã‚’ã‚ã‚ŠãŒã¨ã†ã”ã–ã„ã¾ã™ã€‚"

[AlreadyAnswer]
other = "ã™ã§ã«ç­”ãˆã‚’å‡ºã—ã¾ã—ãŸã€‚"